name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: pycodestyle $(git ls-files "*py")
      
  unit_tests:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m unittest test_utils
